//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spreadsheet.Core {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spreadsheet.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Binary operation not supported for operator &apos;{0}&apos;.
        /// </summary>
        internal static string BinaryOperationNotSupported {
            get {
                return ResourceManager.GetString("BinaryOperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Circular reference.
        /// </summary>
        internal static string CircularReference {
            get {
                return ResourceManager.GetString("CircularReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на End of expression.
        /// </summary>
        internal static string EndOfExpression {
            get {
                return ResourceManager.GetString("EndOfExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to read spreadsheet size from line &apos;{0}&apos;.
        /// </summary>
        internal static string FailedToReadSpreadsheetSize {
            get {
                return ResourceManager.GetString("FailedToReadSpreadsheetSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Integer value is too big, consider to use long.
        /// </summary>
        internal static string IntegerToBig {
            get {
                return ResourceManager.GetString("IntegerToBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cell column can`t be negative.
        /// </summary>
        internal static string NegativeCellColumn {
            get {
                return ResourceManager.GetString("NegativeCellColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cell row can`t be negative.
        /// </summary>
        internal static string NegativeCellRow {
            get {
                return ResourceManager.GetString("NegativeCellRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nothing.
        /// </summary>
        internal static string Nothing {
            get {
                return ResourceManager.GetString("Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unary operation not supported for operator &apos;{0}&apos;.
        /// </summary>
        internal static string UnaryOperationNotSupported {
            get {
                return ResourceManager.GetString("UnaryOperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown cell start &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownCellStart {
            get {
                return ResourceManager.GetString("UnknownCellStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown expression element &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownExpressionElement {
            get {
                return ResourceManager.GetString("UnknownExpressionElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to parse cell address &apos;{0}&apos;.
        /// </summary>
        internal static string WrongCellAddress {
            get {
                return ResourceManager.GetString("WrongCellAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cell column is more then spreadsheet size.
        /// </summary>
        internal static string WrongCellColumn {
            get {
                return ResourceManager.GetString("WrongCellColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cell row is more then spreadsheet size.
        /// </summary>
        internal static string WrongCellRow {
            get {
                return ResourceManager.GetString("WrongCellRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong content type. Expected &apos;{1}&apos; but was &apos;{0}&apos;.
        /// </summary>
        internal static string WrongTokenType {
            get {
                return ResourceManager.GetString("WrongTokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong data type in expression. Expected &apos;{0}&apos; but was &apos;{1}&apos;.
        /// </summary>
        internal static string WrongTypeError {
            get {
                return ResourceManager.GetString("WrongTypeError", resourceCulture);
            }
        }
    }
}
